query GetPost($id: ID!) {
  post(id: $id) {
    id
    url
    relativeUrl
    fields {
      key
      value
      relationEntities {
        __typename
        members {
          __typename
          ...MemberFields
        }
        posts {
          __typename
          ...PostFields
        }
      }
    }
    reactionsCount
    createdAt
    publishedAt
    ownerId
    status
    spaceId
    title
    description
    thumbnail {
      ...MediaFields
    }
    customSeoDetail {
      description
      noIndex
      thumbnail {
        ... on Image {
          id
          url
          width
          height
        }
      }
      thumbnailId
      title
      canonicalUrl
    }
  }
}

fragment MediaFields on Media {
  __typename
  ... on Emoji {
    __typename
    id
    text
  }
  ... on File {
    __typename
    downloadUrl
    extension
    id
    name
    size
    status
    url
  }
  ... on Image {
    __typename
    downloadUrl
    height
    id
    name
    url
    urls {
      __typename
      full
      large
      medium
      small
      thumb
    }
    width
  }
}

fragment MemberFields on Member {
  createdAt
  displayName
  email
  id
  name
  profilePicture {
    ...MediaFields
  }
  profilePictureId
  relativeUrl
  roleId
  url
  username
  verifiedAt
}

fragment PostFields on Post {
  id
  url
  title
  createdAt
  createdById
  description
  ownerId
  publishedAt
  reactionsCount
  relativeUrl
  spaceId
  status
  textContent
}
